version: '2'

services:
  nginx:
    image: 'nginx:1.15'
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx/configs/site.conf:/etc/nginx/conf.d/site.conf
      - ./docker/nginx/logs/:/var/log/nginx/
      - ./api-www:/var/www/html/api.gt-music-app.com
      - ./admin-www:/var/www/html/admin.gt-music-app.com
    links:
      - php

  php:
    build:
      context: '.\docker\php'
    volumes:
      - ./api-www:/var/www/html/api.gt-music-app.com
      - ./admin-www:/var/www/html/admin.gt-music-app.com